apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loaduyji2583-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loaduyji2583-tenant-component
    app.kubernetes.io/part-of: loaduyji2583-tenant-app
  name: loaduyji2583-tenant-component
  namespace: loaduyji2583-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loaduyji2583-tenant-component
status:
  loadBalancer: {}
